name: build and test
on:
  push:
  pull_request_target:
    types: [opened, synchronize, edited]
concurrency: ci-${{ github.ref }}-${{ github.event_name }}
env:
  TERRAFORM_VERSION: '1'
jobs:
  test:
    runs-on: ubuntu-latest
    if: ((github.actor == 'dependabot[bot]' && github.event_name == 'pull_request_target') || (github.actor != 'dependabot[bot]' && github.event_name == 'push'))
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4
        if: github.event_name == 'push'
        with:
          fetch-depth: 0
          persist-credentials: false
      - uses: actions/checkout@v4
        if: github.event_name == 'pull_request_target'
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - uses: actions/setup-node@v4
        with:
          node-version: '18.14.2'
      - name: setup terraform
        uses: hashicorp/setup-terraform@v3
        with:
            terraform_version: ${{ env.TERRAFORM_VERSION }}
      - name: test
        run: |
          npm ci
          npm test
      - name: update docs
        uses: terraform-docs/gh-actions@v1.4.0
        with:
          working-dir: .
          output-file: README.md
          output-method: inject
          git-push: "false"
      - name: approve-dependabot
        if: github.event_name == 'pull_request_target' && github.actor == 'dependabot[bot]'
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PA_TOKEN }}
        run: |
          gh pr review --approve || true
          gh pr merge --auto --rebase || true
      - name: publish
        env:
          GH_TOKEN: ${{ secrets.GH_PA_TOKEN }}
        run: |
          npm run release
  lint-commits:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request_target' || (github.ref != 'refs/heads/main' && github.event_name == 'push')
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        if: github.actor != 'dependabot[bot]'
      - name: install
        if: github.actor != 'dependabot[bot]'
        run: npm i --package-lock=false @commitlint/cli @commitlint/config-conventional conventional-commit-types conventional-changelog-angular
      - name: commitlint
        if: github.actor != 'dependabot[bot]'
        run: ./node_modules/.bin/commitlint --from HEAD~${{ github.event.pull_request.commits }} --to HEAD
